import React from 'react'

// Route = /about

export const metadata = {
    title: 'About Avesh',
    description: 'Generated by create next app',
    keywords:'nextjs'
  }

const AboutPage = () => {
  return (
    <div>
      <h1>This is About Page</h1>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit vel, recusandae perferendis dolorem fugiat, soluta amet sed illo aliquam culpa eveniet nihil harum iure, ipsam tempore neque cupiditate iste commodi.</p>
    </div>
  )
}

export default AboutPage
