import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

// This is the main layout of the project you can import your header and footer here and set your project layout as you want.

//We can also directly import fonts from the google
import { Inter } from "next/font/google";

import { Poppins } from "next/font/google";

const poppins = Poppins({ weight: ["400", "500"], subsets: ["latin"] });

const inter = Inter({ subsets: ["latin"] });

// This is title of html what is your project name, all the meta tags of the html can be here
export const metadata = {
  title: "Avesh Next-js",
  description: "Generated by create next app",
  keywords: "nextjs",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <main className="container">
          <Header />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
